name: Daily Puzzle Assignment
on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  assign-puzzle:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase function
        run: |
          curl -X POST https://kzdbsuhqlkgpoabt.supabase.co/functions/v1/daily-puzzle \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json"